server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_angular_springboot
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true


